spring.application.name=erp-backend

# ===============================
# SUPABASE DATABASE - SESSION POOLER
# ===============================
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xppolgfuvrvhpqmcbrkp
spring.datasource.password=AdityaNale@18
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY - TEMPORARILY DISABLED
# ===============================
spring.flyway.enabled=false

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-ms=3600000
app.security.refresh-token.expiration-ms=604800000

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.cubeage.erp=DEBUG
logging.level.org.hibernate.SQL=DEBUG