package com.cubeage.erp.projects.service.impl;
import com.cubeage.erp.projects.dto.request.*; import com.cubeage.erp.projects.dto.response.BudgetSummaryResponse;
import com.cubeage.erp.projects.entity.*; import com.cubeage.erp.projects.enums.BudgetCostType; import com.cubeage.erp.projects.exception.*;
import com.cubeage.erp.projects.repository.*; import com.cubeage.erp.projects.service.BudgetService;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class BudgetServiceImpl implements BudgetService {
 private final ProjectRepository projectRepository; private final ProjectBudgetRepository budgetRepository; private final ProjectCostEntryRepository costRepository; private final ProjectTaskRepository taskRepository;
 @Override public BudgetSummaryResponse setPlanned(Long tenantId,Long projectId,BudgetRequest r){Project p=project(tenantId,projectId);ProjectBudget b=budgetRepository.findByTenantIdAndProject_IdAndCostType(tenantId,projectId,r.costType()).orElseGet(ProjectBudget::new);b.setTenantId(tenantId);b.setProject(p);b.setCostType(r.costType());b.setPlannedAmount(r.plannedAmount());if(b.getActualAmount()==null)b.setActualAmount(BigDecimal.ZERO);budgetRepository.save(b);p.setPlannedBudget(budgetRepository.findByTenantIdAndProject_Id(tenantId,projectId).stream().map(ProjectBudget::getPlannedAmount).reduce(BigDecimal.ZERO,BigDecimal::add));projectRepository.save(p);return summary(tenantId,projectId);}
 @Override public BudgetSummaryResponse addCost(Long tenantId,Long projectId,CostEntryRequest r){Project p=project(tenantId,projectId);ProjectTask t=null;if(r.taskId()!=null){t=taskRepository.findByIdAndTenantId(r.taskId(),tenantId).orElseThrow(()->new TaskNotFoundException(r.taskId()));if(!t.getProject().getId().equals(projectId))throw new ProjectValidationException("Task does not belong to project");}costRepository.save(ProjectCostEntry.builder().tenantId(tenantId).project(p).task(t).costType(r.costType()).amount(r.amount()).costDate(r.costDate()).description(r.description()).referenceType(r.referenceType()).referenceId(r.referenceId()).build());ProjectBudget b=budgetRepository.findByTenantIdAndProject_IdAndCostType(tenantId,projectId,r.costType()).orElseGet(()->ProjectBudget.builder().tenantId(tenantId).project(p).costType(r.costType()).plannedAmount(BigDecimal.ZERO).actualAmount(BigDecimal.ZERO).build());b.setActualAmount(b.getActualAmount().add(r.amount()));budgetRepository.save(b);p.setActualBudget(costRepository.totalActualCost(tenantId,projectId));projectRepository.save(p);return summary(tenantId,projectId);}
 @Override @Transactional(readOnly=true) public BudgetSummaryResponse summary(Long tenantId,Long projectId){Project p=project(tenantId,projectId);var rows=budgetRepository.findByTenantIdAndProject_Id(tenantId,projectId);Map<String,BigDecimal> planned=new LinkedHashMap<>(),actual=new LinkedHashMap<>();for(BudgetCostType t:BudgetCostType.values()){planned.put(t.name().toLowerCase(),BigDecimal.ZERO);actual.put(t.name().toLowerCase(),BigDecimal.ZERO);}for(ProjectBudget b:rows){planned.put(b.getCostType().name().toLowerCase(),b.getPlannedAmount());actual.put(b.getCostType().name().toLowerCase(),b.getActualAmount());}BigDecimal plan=p.getPlannedBudget()==null?BigDecimal.ZERO:p.getPlannedBudget();BigDecimal act=p.getActualBudget()==null?BigDecimal.ZERO:p.getActualBudget();BigDecimal variance=plan.subtract(act);BigDecimal util=plan.signum()==0?BigDecimal.ZERO:act.multiply(BigDecimal.valueOf(100)).divide(plan,2,RoundingMode.HALF_UP);BigDecimal threshold=BigDecimal.valueOf(100).add(p.getBudgetAlertThresholdPercent()==null?BigDecimal.TEN:p.getBudgetAlertThresholdPercent());return new BudgetSummaryResponse(projectId,plan,act,variance,util,util.compareTo(threshold)>0,planned,actual);}
 private Project project(Long tenantId,Long id){return projectRepository.findByIdAndTenantId(id,tenantId).orElseThrow(()->new ProjectNotFoundException(id));}
}
