package com.cubeage.erp.projects.service.impl;
import com.cubeage.erp.projects.dto.response.AiInsightResponse; import com.cubeage.erp.projects.entity.*; import com.cubeage.erp.projects.enums.*;
import com.cubeage.erp.projects.exception.ProjectNotFoundException; import com.cubeage.erp.projects.mapper.ProjectMapper; import com.cubeage.erp.projects.repository.*; import com.cubeage.erp.projects.service.ProjectAiService;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.LocalDate; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class ProjectAiServiceImpl implements ProjectAiService {
 private final ProjectRepository projectRepository; private final ProjectTaskRepository taskRepository; private final ProjectMemberRepository memberRepository; private final ProjectRiskRepository riskRepository; private final ProjectAiInsightRepository insightRepository; private final ProjectMapper mapper;
 @Override public List<AiInsightResponse> analyze(Long tenantId,Long projectId){Project p=projectRepository.findByIdAndTenantId(projectId,tenantId).orElseThrow(()->new ProjectNotFoundException(projectId));var tasks=taskRepository.findByTenantIdAndProject_IdOrderByPlannedStartDateAsc(tenantId,projectId);long overdue=tasks.stream().filter(t->t.getStatus()!=TaskStatus.COMPLETED&&t.getPlannedEndDate().isBefore(LocalDate.now())).count();long blocked=tasks.stream().filter(t->t.getStatus()==TaskStatus.BLOCKED).count();long atRisk=tasks.stream().filter(ProjectTask::getAtRisk).count();int delayScore=(int)Math.min(100,overdue*15+blocked*20+atRisk*10);String factors="Overdue tasks: "+overdue+", blocked tasks: "+blocked+", dependency-risk tasks: "+atRisk;save(p,AiInsightType.DELAY_PREDICTION,delayScore,delayScore>=60?"Project has a high likelihood of schedule delay":delayScore>=30?"Project has a moderate delay risk":"Project schedule risk is currently low",factors,delayScore>=30?"Review critical dependencies and reassign capacity to overdue/blocked work":"Continue monitoring task progress");
  var overloaded=new ArrayList<String>();for(ProjectMember m:memberRepository.findByTenantIdAndProject_IdAndActiveTrue(tenantId,projectId)){BigDecimal total=memberRepository.findByTenantIdAndUserIdAndActiveTrue(tenantId,m.getUserId()).stream().map(ProjectMember::getAllocationPercent).reduce(BigDecimal.ZERO,BigDecimal::add);if(total.compareTo(BigDecimal.valueOf(100))>0)overloaded.add((m.getUserName()==null?"User "+m.getUserId():m.getUserName())+"="+total+"%");}int resourceScore=Math.min(100,overloaded.size()*30);save(p,AiInsightType.RESOURCE_RECOMMENDATION,resourceScore,overloaded.isEmpty()?"No cross-project over-allocation detected":"Resource reallocation is recommended",overloaded.isEmpty()?"No member exceeds 100% allocation":String.join(", ",overloaded),overloaded.isEmpty()?"Keep current allocation":"Reduce overloaded allocations and shift tasks to available members");
  var risks=riskRepository.findByTenantIdAndProject_IdOrderByCreatedAtDesc(tenantId,projectId);long open=risks.stream().filter(r->r.getStatus()!=RiskStatus.RESOLVED&&r.getStatus()!=RiskStatus.CLOSED).count();BigDecimal plan=p.getPlannedBudget()==null?BigDecimal.ZERO:p.getPlannedBudget();BigDecimal actual=p.getActualBudget()==null?BigDecimal.ZERO:p.getActualBudget();BigDecimal utilization=plan.signum()==0?BigDecimal.ZERO:actual.multiply(BigDecimal.valueOf(100)).divide(plan,2,RoundingMode.HALF_UP);int riskScore=(int)Math.min(100,open*10+(utilization.compareTo(BigDecimal.valueOf(100))>0?40:0)+atRisk*5);save(p,AiInsightType.RISK_ANALYSIS,riskScore,"Project risk analysis updated","Open risks: "+open+", budget utilization: "+utilization+"%, at-risk tasks: "+atRisk,riskScore>=50?"Prioritize mitigation of schedule, budget and resource risks":"Maintain regular risk reviews");
  if(utilization.compareTo(BigDecimal.valueOf(100).add(p.getBudgetAlertThresholdPercent()))>0)save(p,AiInsightType.BUDGET_WARNING,Math.min(100,utilization.intValue()),"Budget threshold exceeded","Budget utilization is "+utilization+"% and configured alert threshold is "+p.getBudgetAlertThresholdPercent()+"% above plan","Review cost entries and obtain corrective budget approval");
  return insights(tenantId,projectId);}
 @Override @Transactional(readOnly=true) public List<AiInsightResponse> insights(Long tenantId,Long projectId){return insightRepository.findByTenantIdAndProject_IdAndActiveTrueOrderByCreatedAtDesc(tenantId,projectId).stream().map(mapper::insight).toList();}
 private void save(Project p,AiInsightType type,int score,String summary,String factors,String recommendation){for(ProjectAiInsight old:insightRepository.findByTenantIdAndProject_IdAndTypeAndActiveTrue(p.getTenantId(),p.getId(),type)){old.setActive(false);insightRepository.save(old);}insightRepository.save(ProjectAiInsight.builder().tenantId(p.getTenantId()).project(p).type(type).score(score).summary(summary).contributingFactors(factors).recommendation(recommendation).active(true).build());}
}
