package com.cubeage.erp.projects.service.impl;
import com.cubeage.erp.projects.dto.request.*; import com.cubeage.erp.projects.dto.response.TaskResponse;
import com.cubeage.erp.projects.entity.*; import com.cubeage.erp.projects.enums.*; import com.cubeage.erp.projects.exception.*;
import com.cubeage.erp.projects.mapper.ProjectMapper; import com.cubeage.erp.projects.repository.*; import com.cubeage.erp.projects.service.TaskService;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.LocalDate; import java.util.List;
@Service @RequiredArgsConstructor @Transactional
public class TaskServiceImpl implements TaskService {
 private final ProjectRepository projectRepository; private final ProjectTaskRepository repository; private final ProjectMilestoneRepository milestoneRepository; private final TaskDependencyRepository dependencyRepository; private final ProjectMapper mapper;
 @Override public TaskResponse create(Long tenantId,Long projectId,CreateTaskRequest r){Project p=projectRepository.findByIdAndTenantId(projectId,tenantId).orElseThrow(()->new ProjectNotFoundException(projectId)); if(r.plannedEndDate().isBefore(r.plannedStartDate()))throw new ProjectValidationException("Task end date cannot be before start date"); ProjectMilestone m=null;if(r.milestoneId()!=null){m=milestoneRepository.findByIdAndTenantId(r.milestoneId(),tenantId).orElseThrow(()->new MilestoneNotFoundException(r.milestoneId()));if(!m.getProject().getId().equals(projectId))throw new ProjectValidationException("Milestone does not belong to project");}ProjectTask t=ProjectTask.builder().tenantId(tenantId).project(p).milestone(m).parentTaskId(r.parentTaskId()).title(r.title()).description(r.description()).assignedToUserId(r.assignedToUserId()).assignedToName(r.assignedToName()).plannedStartDate(r.plannedStartDate()).plannedEndDate(r.plannedEndDate()).status(TaskStatus.TODO).priority(r.priority()).progressPercent(0).plannedHours(r.plannedHours()).actualHours(BigDecimal.ZERO).atRisk(false).build();return mapper.task(repository.save(t));}
 @Override public TaskResponse update(Long tenantId,Long id,UpdateTaskRequest r){ProjectTask t=entity(tenantId,id);if(r.title()!=null)t.setTitle(r.title());if(r.description()!=null)t.setDescription(r.description());if(r.assignedToUserId()!=null)t.setAssignedToUserId(r.assignedToUserId());if(r.assignedToName()!=null)t.setAssignedToName(r.assignedToName());if(r.plannedStartDate()!=null)t.setPlannedStartDate(r.plannedStartDate());if(r.plannedEndDate()!=null)t.setPlannedEndDate(r.plannedEndDate());if(t.getPlannedEndDate().isBefore(t.getPlannedStartDate()))throw new ProjectValidationException("Task end date cannot be before start date");if(r.actualStartDate()!=null)t.setActualStartDate(r.actualStartDate());if(r.actualEndDate()!=null)t.setActualEndDate(r.actualEndDate());if(r.status()!=null)t.setStatus(r.status());if(r.priority()!=null)t.setPriority(r.priority());if(r.progressPercent()!=null)t.setProgressPercent(Math.max(0,Math.min(100,r.progressPercent())));if(r.plannedHours()!=null)t.setPlannedHours(r.plannedHours());if(t.getStatus()==TaskStatus.COMPLETED){t.setProgressPercent(100);if(t.getActualEndDate()==null)t.setActualEndDate(LocalDate.now());t.setAtRisk(false);t.setRiskReason(null);}t=repository.save(t);evaluateDependencyRisk(tenantId,id);return mapper.task(t);}
 @Override @Transactional(readOnly=true) public TaskResponse get(Long tenantId,Long id){return mapper.task(entity(tenantId,id));}
 @Override @Transactional(readOnly=true) public List<TaskResponse> list(Long tenantId,Long projectId){return repository.findByTenantIdAndProject_IdOrderByPlannedStartDateAsc(tenantId,projectId).stream().map(mapper::task).toList();}
 @Override public TaskResponse addDependency(Long tenantId,Long taskId,TaskDependencyRequest r){ProjectTask t=entity(tenantId,taskId);ProjectTask d=entity(tenantId,r.dependsOnTaskId());if(t.getId().equals(d.getId()))throw new ProjectValidationException("Task cannot depend on itself");if(!t.getProject().getId().equals(d.getProject().getId()))throw new ProjectValidationException("Dependency must belong to same project");if(!dependencyRepository.existsByTenantIdAndTask_IdAndDependsOnTask_Id(tenantId,taskId,d.getId()))dependencyRepository.save(TaskDependency.builder().tenantId(tenantId).task(t).dependsOnTask(d).build());refreshTaskRisk(tenantId,t);return mapper.task(t);}
 @Override public void evaluateDependencyRisk(Long tenantId,Long dependencyTaskId){for(TaskDependency link:dependencyRepository.findByTenantIdAndDependsOnTask_Id(tenantId,dependencyTaskId))refreshTaskRisk(tenantId,link.getTask());}
 private void refreshTaskRisk(Long tenantId,ProjectTask task){var deps=dependencyRepository.findByTenantIdAndTask_Id(tenantId,task.getId());boolean risk=false;String reason=null;for(TaskDependency d:deps){ProjectTask dep=d.getDependsOnTask();if(dep.getStatus()==TaskStatus.BLOCKED||(dep.getStatus()!=TaskStatus.COMPLETED&&dep.getPlannedEndDate().isBefore(LocalDate.now()))){risk=true;reason="Dependency delayed: "+dep.getTitle();break;}}task.setAtRisk(risk);task.setRiskReason(reason);repository.save(task);}
 private ProjectTask entity(Long tenantId,Long id){return repository.findByIdAndTenantId(id,tenantId).orElseThrow(()->new TaskNotFoundException(id));}
}
