package com.cubeage.erp.projects.service.impl;
import com.cubeage.erp.projects.dto.request.CreateTimesheetRequest; import com.cubeage.erp.projects.dto.response.TimesheetResponse;
import com.cubeage.erp.projects.entity.*; import com.cubeage.erp.projects.enums.*; import com.cubeage.erp.projects.exception.*;
import com.cubeage.erp.projects.mapper.ProjectMapper; import com.cubeage.erp.projects.repository.*; import com.cubeage.erp.projects.service.TimesheetService;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.List;
@Service @RequiredArgsConstructor @Transactional
public class TimesheetServiceImpl implements TimesheetService {
 private final ProjectRepository projectRepository; private final ProjectTaskRepository taskRepository; private final ProjectMemberRepository memberRepository; private final TimesheetRepository repository; private final ProjectMapper mapper;
 @Override public TimesheetResponse create(Long tenantId,Long userId,String userName,CreateTimesheetRequest r){Project p=projectRepository.findByIdAndTenantId(r.projectId(),tenantId).orElseThrow(()->new ProjectNotFoundException(r.projectId()));ProjectTask t=taskRepository.findByIdAndTenantId(r.taskId(),tenantId).orElseThrow(()->new TaskNotFoundException(r.taskId()));if(!t.getProject().getId().equals(p.getId()))throw new ProjectValidationException("Task does not belong to project");if(memberRepository.findByTenantIdAndProject_IdAndUserId(tenantId,p.getId(),userId).filter(ProjectMember::getActive).isEmpty()&&!p.getManagerUserId().equals(userId))throw new ProjectValidationException("User is not assigned to project");Timesheet ts=Timesheet.builder().tenantId(tenantId).project(p).task(t).userId(userId).userName(userName).workDate(r.workDate()).hours(r.hours()).description(r.description()).status(TimesheetStatus.DRAFT).build();return mapper.timesheet(repository.save(ts));}
 @Override public TimesheetResponse submit(Long tenantId,Long userId,Long id){Timesheet t=entity(tenantId,id);if(!t.getUserId().equals(userId))throw new ProjectValidationException("Only timesheet owner can submit");if(t.getStatus()!=TimesheetStatus.DRAFT&&t.getStatus()!=TimesheetStatus.REJECTED)throw new ProjectValidationException("Timesheet cannot be submitted in current status");t.setStatus(TimesheetStatus.SUBMITTED);return mapper.timesheet(repository.save(t));}
 @Override public TimesheetResponse approve(Long tenantId,Long approverId,String approverName,Long id){Timesheet t=entity(tenantId,id);if(t.getStatus()!=TimesheetStatus.SUBMITTED)throw new ProjectValidationException("Only submitted timesheets can be approved");t.setStatus(TimesheetStatus.APPROVED);t.setApprovedByUserId(approverId);t.setApprovedByName(approverName);repository.save(t);BigDecimal total=repository.sumHoursByTaskAndStatus(tenantId,t.getTask().getId(),TimesheetStatus.APPROVED);t.getTask().setActualHours(total);taskRepository.save(t.getTask());return mapper.timesheet(t);}
 @Override public TimesheetResponse reject(Long tenantId,Long approverId,String approverName,Long id){Timesheet t=entity(tenantId,id);if(t.getStatus()!=TimesheetStatus.SUBMITTED)throw new ProjectValidationException("Only submitted timesheets can be rejected");t.setStatus(TimesheetStatus.REJECTED);t.setApprovedByUserId(approverId);t.setApprovedByName(approverName);return mapper.timesheet(repository.save(t));}
 @Override @Transactional(readOnly=true) public List<TimesheetResponse> my(Long tenantId,Long userId){return repository.findByTenantIdAndUserIdOrderByWorkDateDesc(tenantId,userId).stream().map(mapper::timesheet).toList();}
 @Override @Transactional(readOnly=true) public List<TimesheetResponse> project(Long tenantId,Long projectId){return repository.findByTenantIdAndProject_IdOrderByWorkDateDesc(tenantId,projectId).stream().map(mapper::timesheet).toList();}
 private Timesheet entity(Long tenantId,Long id){return repository.findByIdAndTenantId(id,tenantId).orElseThrow(()->new TimesheetNotFoundException(id));}
}
