package com.cubeage.erp.projects.mapper;
import com.cubeage.erp.projects.dto.response.*; import com.cubeage.erp.projects.entity.*; import com.cubeage.erp.projects.repository.TaskDependencyRepository;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Component;
@Component @RequiredArgsConstructor
public class ProjectMapper {
 private final TaskDependencyRepository dependencyRepository;
 public ProjectResponse project(Project p){return new ProjectResponse(p.getId(),p.getProjectCode(),p.getName(),p.getDescription(),p.getCustomerId(),p.getCustomerName(),p.getManagerUserId(),p.getManagerName(),p.getBranchId(),p.getDepartmentId(),p.getCostCenterId(),p.getStartDate(),p.getEndDate(),p.getStatus().name().toLowerCase(),p.getPriority().name().toLowerCase(),p.getPlannedBudget(),p.getActualBudget(),p.getBudgetAlertThresholdPercent(),p.getProgressPercent(),p.getCreatedAt());}
 public MilestoneResponse milestone(ProjectMilestone m){return new MilestoneResponse(m.getId(),m.getProject().getId(),m.getName(),m.getDescription(),m.getPlannedDate(),m.getCompletedDate(),m.getStatus().name().toLowerCase(),m.getProgressPercent());}
 public TaskResponse task(ProjectTask t){var deps=dependencyRepository.findByTenantIdAndTask_Id(t.getTenantId(),t.getId()).stream().map(d->d.getDependsOnTask().getId()).toList(); return new TaskResponse(t.getId(),t.getProject().getId(),t.getMilestone()==null?null:t.getMilestone().getId(),t.getParentTaskId(),t.getTitle(),t.getDescription(),t.getAssignedToUserId(),t.getAssignedToName(),t.getPlannedStartDate(),t.getPlannedEndDate(),t.getActualStartDate(),t.getActualEndDate(),t.getStatus().name().toLowerCase(),t.getPriority().name().toLowerCase(),t.getProgressPercent(),t.getPlannedHours(),t.getActualHours(),t.getAtRisk(),t.getRiskReason(),deps);}
 public ProjectMemberResponse member(ProjectMember m){return new ProjectMemberResponse(m.getId(),m.getProject().getId(),m.getUserId(),m.getUserName(),m.getRole().name().toLowerCase(),m.getAllocationPercent(),m.getFromDate(),m.getToDate(),m.getActive());}
 public TimesheetResponse timesheet(Timesheet t){return new TimesheetResponse(t.getId(),t.getProject().getId(),t.getTask().getId(),t.getUserId(),t.getUserName(),t.getWorkDate(),t.getHours(),t.getDescription(),t.getStatus().name().toLowerCase(),t.getApprovedByUserId(),t.getApprovedByName());}
 public RiskResponse risk(ProjectRisk r){return new RiskResponse(r.getId(),r.getProject().getId(),r.getTask()==null?null:r.getTask().getId(),r.getTitle(),r.getDescription(),r.getType().name().toLowerCase(),r.getLevel().name().toLowerCase(),r.getStatus().name().toLowerCase(),r.getProbabilityPercent(),r.getImpactScore(),r.getMitigationPlan(),r.getOwnerUserId(),r.getOwnerName(),r.getAiGenerated());}
 public AiInsightResponse insight(ProjectAiInsight i){return new AiInsightResponse(i.getId(),i.getProject().getId(),i.getType().name().toLowerCase(),i.getScore(),i.getSummary(),i.getContributingFactors(),i.getRecommendation(),i.getActive());}
 public DocumentLinkResponse document(ProjectDocumentLink d){return new DocumentLinkResponse(d.getId(),d.getProject().getId(),d.getTask()==null?null:d.getTask().getId(),d.getDocumentId(),d.getDocumentTitle());}
}
