export const APP_NAME = 'SmartERP AI'
export const APP_VERSION = '1.0.0'
export const DEFAULT_PAGE_SIZE = 10
export const DEFAULT_CURRENCY = 'INR'
export const DEFAULT_LOCALE = 'en-IN'




export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  SALES_MANAGER: "SALES_MANAGER",
  HR_MANAGER: "HR_MANAGER",
  OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
  EMPLOYEE: "EMPLOYEE",
};